version: '3'

volumes:
  postgres_data:
  logs:

# the below directive makes it possible to run tests behind a VPN
# (feel free to comment it out if it breaks anything for you!)

networks:
  default:
    external:
      name: localdev


services:

  db:
    image: postgres:12
    container_name: signalboost_test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  test_runner:
    image: registry.0xacab.org/team-friendo/signalboost/signalboost:latest
    container_name: signalboost_test_runner
    entrypoint: /signalboost/bin/entrypoint/test-integration
    #TODO(aguestuser|2020-03-20): we should probably have an .env.test?
    env_file: .env.dev
    environment:
      PROJECT_ROOT: "$PWD"
      NODE_ENV: "test"
      DEFAULT_LANGUAGE: "${DEFAULT_LANGUAGE:-EN}"
      INTEGRATION_TEST: 1
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./.sequelizerc:/signalboost/.sequelizerc
      - ./app:/signalboost/app
      - ./bin:/signalboost/bin
      - ./node_modules:/signalboost/node_modules
      - ./package.json:/signalboost/package.json
      - ./test:/signalboost/test
      - ./yarn.lock:/signalboost/yarn.lock
      - /var/run/docker.sock:/var/run/docker.sock
