#!/usr/bin/env bash

pushd `pwd` > /dev/null # store current dir
cd `dirname "$0"` # cd to script path

command=$1

if [[ $command == "-h" ]] || [[ $command == "--help" ]];then
  command=help
fi  

echo ""

print_usage(){
  echo "Whoops! You invoked \`boost\` without a valid command!"
  echo ""
  echo "Valid commands include:"
  echo ""
  echo "  help"
  echo "  add-admin"
  echo "  create-channel"
  echo "  create-number"
  echo "  list-channels"
  echo "  list-numbers"
  echo "  release-numbers"
  echo "  recycle"
  echo ""
  echo "To learn what these commands do, run:"
  echo ""
  echo "  boost help"
  echo ""
}

if [[ $command != "help" ]] &&
     [[ $command != "add-admin" ]] &&
     [[ $command != "create-channel" ]] &&
     [[ $command != "create-number" ]] &&
     [[ $command != "list-channels" ]] &&
     [[ $command != "list-numbers" ]] &&
     [[ $command != "release-numbers" ]] &&
     [[ $command != "recycle" ]]
then
  print_usage
  exit 1
else
  ./boost-commands/${command} "${@:2}"
fi

popd > /dev/null # return to original dir
