#!/usr/bin/env bash

if [ ${USER} != 'root' ]
then
  echo "[OOPS]: you need to run this script as root. try running 'sudo ./cli/install ' instead!"
  exit 1
fi

pushd `pwd` > /dev/null # store current dir
cd `dirname "$0"` # cd to script path
cli_dir=`pwd`

echo "Adding '$cli_dir' to your \$PATH..."

cd /usr/local/bin/
ln -s ${cli_dir}/boost boost
ln -s ${cli_dir}/boost-commands boost-commands

# echo "export PATH=\"\$PATH:${PWD}\"" >> ~/.bashrc
# . ~/.bashrcq

echo "Done!"
echo ""
echo "For instructions run:"
echo ""
echo "  boost help"
echo ""

popd > /dev/null
