#!/usr/bin/env bash

echo "\
boost cli supports the following commands:

  help
    - shows this dialogue

  new_channel -p <chan_phone_number> -n <chan_name> -a <admins> -u <api_url>
    - activates a channel with provied phone number, name, and admins via registrar at provided url

  new_numbers -a <area_code> -n <numbers_desired> -u <api_url>
    - purchases n new twilio numbers and registers them w/ signal via registrar at provided url

  register_numbers -u <api_url>
    - registers all purchased twilio numbers with signal

  list_numbers -u <api_url>
    - lists all numbers purchased from twilio (no channel info included)

  release_number <sid>
    - releases a twilio number with the given sid

  release_numbers <path>
    - releases all twilio numbers with sids listed at given path

for more detailed instructions on any command, run:

  boost <command> -h
"
