#!/usr/bin/env bash

if [[ $1 == "-h" ]] || [[ $1 == "--help" ]];then
  echo "This command retrieves active phone numbers. You may find it useful for:"
  echo ""
  echo "(1) discovering inactive phone numbers to use for new channels"
  echo "(2) retrieving twilio sids for releasing phone numbers (with boost release_numbers)"
  echo ""
  echo "valid options are:"
  echo ""
#  echo "-active: will return only active phone numbers (used in channels)"
#  echo "-inactive: will return only active phone numbers (used in channels)"
  echo "-u : url to target (in dev, use signalboost.ngrok.io)";
  echo ""
  exit 1
fi

echo "--- checking environment..."

if [ -z $SIGNALBOOST_API_TOKEN ];then
  echo "--- ERROR: no SIGNALBOOST_API_TOKEN found. try \`\$ source .env\`"
  exit 1
fi

while getopts ":u:" opt; do
  case "$opt" in
    u)
      url="$OPTARG"
      ;;
  esac
done

if [ -z $url ];then url=${SIGNALBOOST_HOST_URL}; fi

echo "--- fetching numbers..."

curl -s \
     -H "Content-Type: application/json" \
     -H "Token: $SIGNALBOOST_API_TOKEN" \
     https://${url}/phoneNumbers | jq

popd > /dev/null
