#!/usr/bin/env bash

if [[ $1 == "-h" ]] || [[ $1 == "--help" ]];then
  echo "this command creates channels from verified phone numbers. valid options are:"
  echo ""
  echo "-p : phone number of channel to activate";
  echo "-n : name to give to the channel once it is activated";
  echo "-b : comma-delimited list of publisher phone numbers";
  echo "-u : url to target (in dev, use signalboost.ngrok.io)";
  echo ""
  exit 1
fi

echo "--- checking environment and args..."

if [ -z $SIGNALBOOST_API_TOKEN ];then
  echo "--- ERROR: no SIGNALBOOST_API_TOKEN found. try \`\$ set -a && source .env && set +a\`"
  exit 1
fi

while getopts ":p:n:b:u:" opt; do
  case "$opt" in
    p)
      phone_number="$OPTARG"
      ;;
    n)
      name="$OPTARG"
      ;;
    b)
      publishers="$OPTARG"
      ;;
    u)
      url="$OPTARG"
      ;;
  esac
done

if [[ ! $phone_number =~ ^\+(1|52)[0-9]{10}$ ]];then
  echo "> ERROR: -p must be a 10 digit phone number prefixed by a country code (+1 or +52)"
  exit 1
fi

if [ -z "$name" ];then
  echo "> ERROR: -n (channel name) may not be empty"
  exit 1;
fi

if [ -z "$publishers" ]
then
  echo "> ERROR: you must provide at least one publisher after the -b flag to create a channel"
  exit 1
elif [[ ! $publishers =~ ^(\+(1|52)[0-9]{10}(,?))+$ ]];then
  echo "> ERROR: -a must be a  comma-delimited list of 10 digit phone numbers prefixed by a country code"
  exit 1
else
  # convert comma-delimited list of numbers
  # into string representation of array of string representations of numbers
  publishers="[\"$(echo $publishers | sed -re "s/,/\", \"/g")\"]"
fi

if [ -z $url ];then url=${SIGNALBOOST_HOST_URL}; fi

echo "--- provisioning new channel [${name}] on phone number ${phone_number} at url ${url}"

curl -s -X POST \
     -H "Content-Type: application/json" \
     -H "Token: $SIGNALBOOST_API_TOKEN" \
     -d "{ \"phoneNumber\": \"$phone_number\", \"name\": \"$name\", \"publishers\":$publishers }" \
     https://${url}/channels | jq
