#!/usr/bin/env bash

if [[ $1 == "-h" ]] || [[ $1 == "--help" ]];then
  echo "this command registers all purchased twilio numbers with signal. valid options are:"
  echo ""
  echo "-u : url to target (default: prod ip address; in dev, use signalboost.ngrok.io)";
  echo ""
  exit 1
fi

echo "--- checking environment..."

if [ -z $SIGNALBOOST_API_TOKEN ];then
  echo "--- ERROR: no SIGNALBOOST_API_TOKEN found. try \`\$ set -a && source .env && set +a\`"
  exit 1
fi

while getopts ":u:" opt; do
  case "$opt" in
    u)
      url="$OPTARG"
      ;;
  esac
done

if [ -z $url ];then url=${SIGNALBOOST_HOST_URL}; fi

echo "--- registering all purchased phone numbers at url ${url}"

curl -s -X POST \
     -H "Content-Type: application/json" \
     -H "Token: $SIGNALBOOST_API_TOKEN" \
     https://${url}/phoneNumbers/register | jq
