#!/usr/bin/env bash

if [[ $1 == "-h" ]] || [[ $1 == "--help" ]];then
  echo "this command provisions phone numbers in an area code. valid options are:"
  echo ""
  echo "-a : area code to provision numbers in (default: 929)";
  echo "-n : number of phone number to provision (default: 1)";
  echo "-u : url to target (default: prod ip address; in dev, use signalboost.ngrok.io)";
  echo ""
  exit 1
fi

echo "--- checking environment..."

if [ -z $SIGNAL_BOOST_API_TOKEN ];then
  echo "--- ERROR: no SIGNAL_BOOST_API_TOKEN found. try \`\$ source .env\`"
  exit 1
fi

if [ -z $TWILIO_AUTH_TOKEN ];then
  echo "--- ERROR: no TWILIO_AUTH_TOKEN found. try \`\$ source .env\`"
  exit 1
fi

while getopts ":a:n:u:" opt; do
  case "$opt" in
    a)
      area_code="$OPTARG"
      ;;
    n)
      num="$OPTARG"
      ;;
    u)
      url="$OPTARG"
      ;;
  esac
done

if [ -z $num ];then num=1; fi
if [[ ! $num =~ ^[0-9]*$ ]];then
  echo "> ERROR: -n must be a number"
  exit 1;
fi


if [ -z $area_code ];then area_code=929; fi
if [[ ! $area_code =~ ^[0-9]{3}$ ]];then
  echo "> ERROR: -a must be a 3 digit number"
  exit 1
fi

if [ -z $url ];then url=${SIGNAL_BOOST_HOST_IP}; fi

echo "--- provisioning ${num} number(s) with area code ${area_code} at url ${url}"

curl -X POST \
     -H "Content-Type: application/json" \
     -H "Token: $SIGNAL_BOOST_API_TOKEN" \
     -d "{ \"areaCode\": \"$area_code\", \"num\": $num }" \
     http://${url}/phoneNumbers | jq
