module.exports = {
  ACCEPT: ['ACCEPT'],
  ADD: ['ADD'],
  BAN: ['BAN'],
  BROADCAST: ['BROADCAST', '!'],
  CHANNEL: ['CHANNEL'],
  DECLINE: ['DECLINE'],
  DESTROY: ['DESTROY'],
  DESTROY_CONFIRM: ['CONFIRM DESTROY'],
  HELP: ['HELP'],
  HOTLINE_ON: ['HOTLINE ON'],
  HOTLINE_OFF: ['HOTLINE OFF'],
  INFO: ['INFO'],
  INVITE: ['INVITE'],
  JOIN: ['HELLO', 'JOIN', 'ချိတ်ဆက်မည်', '你好'], // includes "JOIN" and "LEAVE" for backwards compatibility + partial language support for other languages besides en/es/de/fr
  LEAVE: ['GOODBYE', 'LEAVE', 'STOP', 'UNSUBSCRIBE', 'နှုတ်ဆက်ပါတယ်', 'kwaheri', '拜拜'],
  PRIVATE: ['PRIVATE', '~'],
  REMOVE: ['REMOVE'],
  REPLY: ['REPLY', '@'],
  REQUEST: ['REQUEST'],
  RESTART: ['BOOST RESTART'],
  SET_LANGUAGE: ['ENGLISH', 'INGLÉS', 'INGLES', 'ANGLAIS', 'ENGLISCH'],
  VOUCH_LEVEL: ['VOUCH LEVEL', 'VOUCHING LEVEL'],
  VOUCHING_ON: ['VOUCHING ON'],
  VOUCHING_OFF: ['VOUCHING OFF'],
  VOUCHING_ADMIN: ['VOUCHING ADMIN'],
}
