#!/usr/bin/env bash

set -e

check-env(){
  echo "--- checking environment.."

  env_file=$1

  if [[ -z $(which jq) ]];then
    echo "--- ERROR: you need the jq program installed to run this command!"
    exit 1
  fi

  if [[ -z ${env_file} ]];then
    if [[ -z ${SIGNALBOOST_ENV_FILE} ]];then
      echo "--- ERROR: no .env path provided."
      echo ""
      echo "    To use the boost utility, you must:"
      echo "    -> define credentials in an .env file in the signalboost project root folder"
      echo "    -> provide a path to the .env file (relative to signalboost project root folder) by either:"
      echo "       -> passing it as an argument to the -e flag"
      echo "       -> assigning it to the \$SIGNALBOOST_ENV_FILE env var"
      echo ""
      exit 1
    else
      env_file=${SIGNALBOOST_ENV_FILE}
    fi
  fi

  source ../../${env_file}

  if [[ -z ${SIGNALBOOST_API_TOKEN} ]];then
      echo "--- ERROR: no SIGNALBOOST_API_TOKEN found in the .env file in ${env_file}"
      exit 1
  fi

  if [[ -z ${SIGNALBOOST_HOST_URL} ]];then

    if [[ ${SIGNALBOOST_ENV} != "production" ]];then
      # fetch the ngrok public url, then strip the everything but the domain name (ie: schema, quotes, etc.)
      echo "--- checking for ngrok url..."

      if [[ "$(uname)" == 'Darwin' ]]
        then # we are in Mac and must use sed -E
          host_url=$(curl --max-time 5 -s localhost:4040/api/tunnels | \
            jq ".tunnels[0].public_url" | \
            sed -E 's/(http|https):\/\///' | \
            cut -c 2- | rev | cut -c 2- | rev)

        else # we are in Linux and may use sed -re
          host_url=$(curl --max-time 5 -s localhost:4040/api/tunnels | \
            jq ".tunnels[0].public_url" | \
            sed -re 's/(http|https):\/\///' | \
            cut -c 2- | rev | cut -c 2- | rev)
      fi

      if [[ -z ${host_url} ]];then
        echo "Sorry, you are trying to run boost against a local dev server, but ngrok does not appear to be running."
        echo "That means we cannot find a proxy to route requests through. Please troubleshoot ngrok and try again!"
        exit 1
      fi

      echo "--- ngrok url: $host_url"
      export SIGNALBOOST_HOST_URL=${host_url}

      else
      echo "--- ERROR: no SIGNALBOOST_HOST_URL found in the .env file in ${env_file}"
      exit 1
    fi
  fi

  if [[ -z ${TWILIO_ACCOUNT_SID} ]];then
    echo "--- ERROR: no TWILIO_ACCOUNT_SID found in the .env file in ${env_file}"
    exit 1
  fi

  if [[ -z ${TWILIO_AUTH_TOKEN} ]];then
    echo "--- ERROR: no TWILIO_AUTH_TOKEN found in the .env file in ${env_file}"
    exit 1
  fi
}
