#!/usr/bin/env bash

if [[ $1 == "-h" ]] || [[ $1 == "--help" ]];then
  echo "this command trusts all safety numbers associated with a member phone number. valid options are:"
  echo ""
  echo "-c: channel phone number (any phone number that user is a member of will work!)";
  echo "-a: admin phone number (required)";
  echo "-e : path to .env file (in dev, use .env.dev)";
  echo ""
  exit 1
fi

pushd `pwd` > /dev/null # store current dir
cd `dirname "$0"` # cd to script path

while getopts ":c:a:e:" opt; do
  case "$opt" in
    c)
      channel_phone_number="$OPTARG"
      ;;
    a)
      admin_phone_number="$OPTARG"
      ;;
    e)
      env_file="$OPTARG"
      ;;
  esac
done

# check env vars are properly defined
source ./_check-env
check-env ${env_file}

if [[ ! ${channel_phone_number} =~ ^\+(1|52)[0-9]{10}$ ]];then
  echo "> ERROR: -c must be a 10 digit phone number prefixed by a country code (+1 or +52)"
  exit 1
fi

if [[ ! ${admin_phone_number} =~ ^\+(1|52)[0-9]{10}$ ]];then
  echo "> ERROR: -a must be a 10 digit phone number prefixed by a country code (+1 or +52)"
  exit 1
fi

echo "--- trusting all safety numbers for user ${phone_number} at url ${SIGNALBOOST_HOST_URL}"

curl -s -X POST \
     -H "Content-Type: application/json" \
     -H "Token: $SIGNALBOOST_API_TOKEN" \
     -d "{ \"channelPhoneNumber\": \"$channel_phone_number\", \"adminPhoneNumber\": \"$admin_phone_number\" }" \
     https://${SIGNALBOOST_HOST_URL}/channels/admins | jq

popd > /dev/null # return to starting directory
