#!/usr/bin/env bash

if [[ $1 == "-h" ]] || [[ $1 == "--help" ]];then
  echo "this command provisions phone numbers in an area code. valid options are:"
  echo "  -n : number of phone numbers to provision (default: 1)";
  echo "  -a : area code to provision numbers in (default: 929)";
  echo "  -e : path to .env file (in dev, use .env.dev)";
  echo ""
  exit 1
fi

pushd `pwd` > /dev/null # store current dir
cd `dirname "$0"` # cd to script path

while getopts ":a:n:e:" opt; do
  case "$opt" in
    a)
      area_code="$OPTARG"
      ;;
    n)
      num="$OPTARG"
      ;;
    e)
      env_file="$OPTARG"
      ;;
  esac
done

# check env vars are properly defined
source ./_check-env
check-env ${env_file}

if [[ -z ${num} ]];then num=1; fi
if [[ ! ${num} =~ ^[0-9]*$ ]];then
  echo "> ERROR: -n must be a number"
  exit 1;
fi


if [[ -z ${area_code} ]]
then
  area_code_kv="\"areaCode\": null"
  area_code="(unspecified)"
elif [[ ! ${area_code} =~ ^[0-9]{3}$ ]];then
  echo "> ERROR: -a must be a 3 digit number"
  exit 1
else
  area_code_kv="\"areaCode\": \"$area_code\""
fi

echo "--- provisioning ${num} number(s) with area code ${area_code} at url ${SIGNALBOOST_HOST_URL}"

curl -s -X POST \
     -H "Content-Type: application/json" \
     -H "Token: $SIGNALBOOST_API_TOKEN" \
     -d "{ $area_code_kv, \"num\": $num }" \
     https://${SIGNALBOOST_HOST_URL}/phoneNumbers | jq

popd > /dev/null # return to starting directory
