#!/usr/bin/env bash

set -e

if [[ $1 == "-h" ]] || [[ $1 == "--help" ]];then
  echo "This command retrieves active channels. Valid options are:"
  echo ""
  echo "-e : path to .env file (for dev, use .env.dev)";
  echo ""
  exit 1
fi

pushd `pwd` > /dev/null # store current dir
cd `dirname "$0"` # cd to script path

while getopts ":e:" opt; do
  case "$opt" in
    e)
      env_file="$OPTARG"
      ;;
  esac
done

# check env vars are properly defined
source ./_check-env
check-env ${env_file}

echo "--- fetching numbers..."

curl -s \
     -H "Content-Type: application/json" \
     -H "Token: $SIGNALBOOST_API_TOKEN" \
     https://"$SIGNALBOOST_HOST_URL"/channels | jq '.'

popd > /dev/null # return to starting directory
