#!/usr/bin/env bash

if [[ $1 == "-h" ]] || [[ $1 == "--help" ]];then
  echo "This command recycles phone numbers to be used with new channels. usage:"
  echo ""
  echo "  boost recycle -n +12223334444,+15556667777"
  echo ""
  echo "Valid options are:"
  echo "  -p : phone numbers to be recycled"
  echo "  -e : path to .env file (in dev, use .env.dev)";
  echo ""
  echo "Warning: This will delete all channel/membership data related to these phone numbers!"
  exit 1
fi

pushd `pwd` > /dev/null # store current dir
cd `dirname "$0"` # cd to script path

while getopts ":p:e:" opt; do
  case "$opt" in
    p)
      phone_numbers="$OPTARG"
      ;;
    e)
      env_file="$OPTARG"
      ;;
  esac
done

# check env vars are properly defined
source ./_check-env
check-env ${env_file}

if [[ -z "$phone_numbers" ]]
then
  echo "> ERROR: you must provide at least one phone number after the -p flag to recycle"
  exit 1
elif [[ ! ${phone_numbers} =~ ^(\+[0-9]{9,15}(,?))+$ ]];then
  echo "> ERROR: -p must be a comma-delimited list of valid phone numbers prefixed by a country code"
  exit 1
fi

curl -s -X POST \
     -H "Content-Type: application/json" \
     -H "Token: $SIGNALBOOST_API_TOKEN" \
     -d "{ \"phoneNumbers\": \"$phone_numbers\" }" \
     https://${SIGNALBOOST_HOST_URL}/phoneNumbers/recycle | jq

popd > /dev/null # return to starting directory
