#!/usr/bin/env bash

if [[ $1 == "-h" ]] || [[ $1 == "--help" ]];then
  echo "this command trusts all safety numbers associated with a user's phone number. valid options are:"
  echo ""
  echo "-p : user phone number";
  echo "-u : url to target (in dev, use signalboost.ngrok.io)";
  echo ""
  exit 1
fi

echo "--- checking environment and args..."

if [ -z $SIGNALBOOST_API_TOKEN ];then
  echo "--- ERROR: no SIGNALBOOST_API_TOKEN found. try \`\$ set -a && source .env && set +a\`"
  exit 1
fi

while getopts ":p:n:s:u:" opt; do
  case "$opt" in
    p)
      phone_number="$OPTARG"
      ;;
    u)
      url="$OPTARG"
      ;;
  esac
done

if [[ ! $phone_number =~ ^\+(1|52)[0-9]{10}$ ]];then
  echo "> ERROR: -p must be a 10 digit phone number prefixed by a country code (+1 or +52)"
  exit 1
fi

if [ -z $url ];then url=${SIGNALBOOST_HOST_URL}; fi

echo "--- trusting all safety numbers for user ${phone_number} at url ${url}"

curl -s -X POST \
     -H "Content-Type: application/json" \
     -H "Token: $SIGNALBOOST_API_TOKEN" \
     -d "{ \"memberPhoneNumber\": \"$phone_number\" }" \
     https://${url}/phoneNumbers/trust | jq
