module.exports = {
  ADD: ['AGREGAR'],
  HELP: ['AYUDA'],
  INFO: ['INFO'],
  JOIN: ['HOLA'],
  LEAVE: ['ADIÓS', 'ADIOS'],
  REMOVE: ['ELIMINAR'],
  RENAME: ['RENOMBRAR'],
  RESPONSES_ON: ['RESPUESTAS ACTIVADAS'],
  RESPONSES_OFF: ['RESPUESTAS DESACTIVADAS'],
}