module.exports = {
  ADD: ['AJOUTER'],
  HELP: ['AIDE'],
  INFO: ['INFO'],
  JOIN: ['ALLÔ', 'ALLO'], 
  LEAVE: ['ADIEU'],
  REMOVE: ['SUPPRIMER'],
  RENAME: ['RENOMMER'],
  RESPONSES_ON: ['RÉPONSES ACTIVÉES', 'REPONSES ACTIVEES'],
  RESPONSES_OFF: ['RÉPONSES DÉSACTIVÉES', 'REPONSES DESACTIVEES'],
  SET_LANGUAGE: ['FRENCH', 'FRANÇAIS', 'FRANCAIS'],
}
